# Generated by Django 5.2.3 on 2025-07-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tecnologia', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_projetos/')),
            ],
        ),
    ]
