# Generated by Django 5.2.3 on 2025-07-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_descricao_alter_projeto_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='publicado',
            field=models.BooleanField(default=True, verbose_name='publicado'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(default=1, upload_to='imagem_progetos', verbose_name='imagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tecnologia',
            field=models.CharField(max_length=100, verbose_name='tecnologia'),
        ),
    ]
