# Generated by Django 5.2.3 on 2025-07-03 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='postagem',
            options={'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='criador_em',
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='ultima_modificacão',
        ),
        migrations.AddField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.postagem', verbose_name='Postagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postagem',
            name='categorias',
            field=models.ManyToManyField(related_name='postagens', to='blog.categoria', verbose_name='Categorias'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='ultima_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificação'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(max_length=60, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='corpo',
            field=models.TextField(verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(max_length=180, verbose_name='Título'),
        ),
    ]
