# Generated by Django 5.2.3 on 2025-07-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comentario_postagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Cometario',
        ),
    ]
